/* eslint-disable react/no-unescaped-entities */
/**
 * Created by yaer on 2019/7/26;
 * @Email 740905172@qq.com
 * */
import "./index.less";
import {useDocumentTitle} from "../../hooks";
import {getAppAttributes} from "../../nativeMethod";

const {packageName} = window.appInfo;


const UserAuthorizationAgreement = (props) => {
  useDocumentTitle(props);

  return (
    <div className="user-authorization-agreement-wrapper">
      <h1>{packageName}</h1>
      <h2>User Authorization</h2>
      <h3>Notification :</h3>
      <p>{packageName} TeCh alld SeFVICe PYIVate Limited Wlll use the online application " {packageName} " to recommend
        Rupee cash loan servlce to the NBFC that you haVe c00perated wlth . The Rupee cash loan service agreement is
        based on the agreement with your loan service agreement .</p>
      <p>
        In order to ensure that you can succeSSfully Sign a loan service agreement with NBFC for
        {packageName} and use Rupee cash loan service to protect your legal rights , and obtain your consent to
        authorize the
        use of your personal information , you should carefully read and ensure that you agree to ablde
        by all the conVentions and terms of this user authorization letter ( hereinafter referred to as " authorization
        " ) .
        Please be sure to read carefully and fully understand all the terms of the power of the authorization , in
        particular , terms that reduce or remove the responsibility of {packageName} , or restrictions on your rights .
        The terms of relief or eXemption may be underlined or bolded to alert you .
      </p>
      <p>
        Unless you have careflllly read and flllly agree to aCcept all terms of this authorization ,
        you do not have the right to use the " {packageName} ," recommended Rupee cash 10an Service .
        Any of your creation of personal accounts , login , use , etc . on " {packageName} " shall be deemed as you have
        carefully
        read and fully agree to be bound by the terms of thls authorization , and the power of this authorization takes
        effect immediately . If you do not accept any of the terms of this authorization , please immediately stop the
        progress .
      </p>
      <h3>TO {packageName} TeCh alld SefVICe PFIVate Limited :</h3>
      <p>
        I have clearly understood that {packageName} Tech and Service Prlvate Limited has recommended Rupee Cash Loan
        SerViceS for me through the online platform " {packageName} " . 1 voluntarily apply fora " {packageName} "
        registered account and accept Moore's
        recommended Rupee cash loan service . In order to ensllre that {packageName} TeCh alld SerVICe priVate Limited
        can obiectively
        and accurately understand my credit information and assess my credit rating and credit line to recommend to the
        relevant NBFC , and inquire and use my personal information with its cooperatlng agency , 1 clearly understand
        the meaning of the following authorized content and agree to irrevocably authorize the following :
      </p>
      <p>
        1 . I clearly understand and agree that {packageName} Te ch alld SeYVice PfiVate Llmited afld
        its cooperating agencies ( hereinafter referred to as " authorized person " ) a
        re authorized to provide , inquire and use my personal information , credit information ,
        and personal information ( includ 讯 9 the bad mformatlon generated by my borrowing ServiCe and 1
        do not need to be separately informed ) arising from the use of " {packageName} " Rupee Cash recommend borrowing
        Servlce for many times during the recommendation and duration of the Rupee Cash Loan Business . The scope of
        personal
        information includes , but is not limited to , my name , Addhaar number , CIBIL information , my faCe
        reCognition information
        , pan card information , address , communication and contact Information , emergency contacts , mobile phone
        contacts ,
        personal photos , bank account information , and personal Credit report ( Including credit assessment report ) ,
        work situatlon , occupatlon , track , related hlstorlcal information in social media acCount ( including
        operatlon 109 ,
        Informatlon record ) and payment data information etc . , and varioustyPes of Informat10ll that Can be llsed
        alofle or in combination with other information to identify my ldentity or reflect my activity .
        {" "}
      </p>
      <p>
        2 . 1 agree , promise and confirm that {packageName} Tech and Service Private Limited can read my mobile
        phone contact list information through APP , and authorize {packageName} Tech and Service Private Limited and
        its cooperating
        third parties ( Includ 讯 9 but notl 而 lted to legally established credit institutions , collection agencies ,
        and post - lending management services ) to use the above information , and this authorization is irrevocable .
        {" "}
      </p>
      <h3>Authorizer statement :</h3>
      <p>
        This authorization is a unilateral commitment made by myself to " authorized person "
        such as {packageName} TeCh alld SeFVICe pyiVate Limited afld its lawful cooperation agencies . Its effectiveness
        is independent ,
        and it is not due to the inValidity of the terms of felated bllsineSS ColltraCtS SllCh as the
        10an SerVICe ContraCt between the allthoriZer and {packageName} and NBFC . 1 understand clearly and CollfiFm
        that this lettey of allthofiZatiofl Wlll become effective and irrevocable upon Collfirmation .
      </p>
      <p>
        The period of this authorization is from the date Whefl 1 has made this allth0YIZat10fl Commitmellt
        alld ellds 011 the termiflatiofl of all the bllsilleSS of the " authorized person " and me . For the avoidance
        of doubt , 1 hereby confirm that , in the SitUatioll that 1 Still haVe a 10all at the aUth0YIZed person without
        a balance ,
        the business relationship between the authorizer and the authorized perS0n stlll eXistS , and the authorized
        person still has the right to authorize the behaVior of the allthofiZer Withiin the authorization.
      </p>
      <p>
        If I have any disputes with the authorized person on the above content ,
        it should flrst be resolved through friendly negotiations , If the negotiations fall ,
        1 agree to Submit the dlspute to the court near the plaintiff . The establishment , validity , performance ,
        interpretation and dispute reS0llltioll of this " PerS0llal IllfoFmatioll Authorization " apply to the law of
        India ( excluding the confliction laws ) .
      </p>
      <p>
        I have been flllly aware ofthemeaningofthe ColltentS of this " PerS0flal Infoymatioll Authorization "
        ( especially the content prompted by bold , "/" or underline ) and the resulting legal effect ,
        and voluntarily make the above authorlzatlon , this " Personal Informatlon Authorization " is my true intention
        . I agree to bear all the Iegal consequences .
      </p>
      <p>Hereby warranties !</p>
    </div>
  );
};


export default UserAuthorizationAgreement;
